baseURL = 'http://hugotemplate.xyz/'
languageCode = 'en-us'
title = 'Hugo Template'
theme = 'hugo-template'
[params]
    author = 'Stan Hoenson'
    description = 'A blog about the downfall of technology (and how to fight against it)'
